/*
 * generated by Xtext 2.25.0
 */
package org.palladiosimulator.dataflow.confidentiality.pcm.querydsl.ide;


/**
 * Use this class to register ide components.
 */
public class PCMDFDConstraintLanguageIdeModule extends AbstractPCMDFDConstraintLanguageIdeModule {
}
